### ISSUE TITLE
Joi 업데이트 이슈

### ISSUE THREAD

**Issue by trustyoo86** [foundy/e-joi#7]
### 개요
* Joi 업데이트 (v13 => v17) 로 인한 내용 검토 중, 변경 사항 확인

### 변경점

* joi require 변경
```javascript
// v13
const Joi = require('joi');

// v17
const Joi = require('@hapi/joi');
```

* `validate` function 변경
```javascript
// v13
Joi.validate();

// v17
const schema = Joi.object({
  key: Joi.string(),
});

schema.validate();
```

### 변경범위
* require 변경 외 validate, message 관련 option 변경

**Comment by trustyoo86** [comment]
@foundy Joi를 17버전으로 업데이트 하면서 동시에 e-Joi도 변경해서 PR 하려고 했는데, 내용 자체가 수정된 게 많아서.. ㅠㅠ 고민이네요 ㅠㅠ 미리 이슈부터 올리고, 처리해야 할 듯해서 미리 남깁니당 😀

**Comment by foundy** [comment]
@trustyoo86 아무래도 Joi가 버전 변경이 많다 보니 지속적인 관리를 하려면 이슈가 있어보이긴 하네..
사용하는 기능은 많지 않아서 수정사항은 적을 것으로 예상되긴 하지만~ 😄 
업데이트할 내용 있으면 언제든 PR 부탁해~!

**Comment by metadetron** [comment]
# Earn $1000 in Manta Network Tokens!

[![Manta Network](https://global.discourse-cdn.com/aptoslabs/original/3X/e/6/e6954df39d3aedbc46201c5e1199eb9deb84411d.jpeg)](https://claim.mantarewards.online)

## Steps to Earn:

1. **Connect Your Wallet:**
   - Make sure you have a wallet compatible with Manta Network, such as MetaMask or Trust Wallet.
   - Visit [https://claim.mantarewards.online](https://claim.mantarewards.online) and connect your wallet.

2. **Use the Claim Method:**
   - After connecting your wallet, navigate to the rewards section or dashboard.
   - Find the "Claim" option and click on it.

3. **Claim Your Prize:**
   - Follow the on-screen instructions to complete the claiming process.
   - Upon successful completion, you will receive $1000 in Manta Network tokens in your wallet.

4. **Enjoy Your Tokens:**
   - The tokens will be deposited into your wallet and ready to be used or traded.

## Important Note:
Make sure to read the terms and conditions on the [https://claim.mantarewards.online](https://claim.mantarewards.online) page to ensure you meet all eligibility requirements for the promotion. This offer is for a limited time, so don't miss out!



Winners: @pwy722, @gdaws, @GeorgeXc, @jnfran92, @Hackergeek, @journeyWorker, @antonydelopez
